# Numpy Tutorials
###    -Deepankar Sharma

In [1]:
import numpy as np
print(np.__version__)

1.19.5


In [2]:
print(np.array([1,2,3,4,5])) # convert the list into numpy array
print(np.array((1,2,3,4,5))) # convert the tuple into numpy array

[1 2 3 4 5]
[1 2 3 4 5]


In [3]:
# np.arange(start, stop, step)
# create range of values in row wise order

val1 = np.arange(50, 100, 3)
print(val1)

[50 53 56 59 62 65 68 71 74 77 80 83 86 89 92 95 98]


In [4]:
tup1 = ('a', 'e', 'i', 'o', 'u') # tuple of alphabets
tup2 = (1, 2, 3, 4, 5) # tuple of numbers
np12 = np.array((tup1, tup2)) # numpy array of two tuples
print(np12)

[['a' 'e' 'i' 'o' 'u']
 ['1' '2' '3' '4' '5']]


In [6]:
# np.zeroes(shape)
# to create an array having all values equal to 0
val1 = np.zeros(8) # an one dimensional array with 8 elements as zeroes
print('1D array: ', val1)
val2 = np.zeros((8,8)) # an two dimensional array with 8*8 elements as zeroes
print('\n2D array: \n', val2)
val3 = np.zeros((2, 2, 2)) # an three dimensional array with 2*2*2 elements as zeroes
print('\n3D array: \n', val3)

1D array:  [0. 0. 0. 0. 0. 0. 0. 0.]

2D array: 
 [[0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]]

3D array: 
 [[[0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]]]


In [7]:
# dipanshu bawa SUPER() method
class A(): 
    def __init__(self):
        print('__init__ of A')
    def feat(self):
        print('feat of A')
class B():
    def __init__(self):
        print('__init__ of B')

class C(A, B):
    def __init__(self):
        print('__init__ of C')
    
    def feat(self):
        super().feat()    

c = C()
c.feat()

__init__ of C
feat of A


In [8]:
# np.ones(shape)
# to create an array having all values equal to 1
val1 = np.ones(8)  # an one dimensional array with 8 elements as ones
print('1D array: ', val1)
val2 = np.ones((8, 8))  # an two dimensional array with 8*8 elements as ones
print('\n2D array: \n', val2)
# an three dimensional array with 8*8*8 elements as ones
val3 = np.ones((8, 8, 8))
print('\n3D array: \n', val3)

1D array:  [1. 1. 1. 1. 1. 1. 1. 1.]

2D array: 
 [[1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1.]]

3D array: 
 [[[1. 1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1.

In [10]:
val = np.ones((4, 5)) # a 4*5 array will all values equal to 1
val*=11 # a 4*5 array with all values equal to 11
print(val)

[[11. 11. 11. 11. 11.]
 [11. 11. 11. 11. 11.]
 [11. 11. 11. 11. 11.]
 [11. 11. 11. 11. 11.]]


In [12]:
# np.linspace(start, stop, num)
# it equally divides the start and stop 'num' times and stores them in the form of an array
val = np.linspace(1, 10, 30) # divides 1 and 10 into 30 equal parts
print(val)

[ 1.          1.31034483  1.62068966  1.93103448  2.24137931  2.55172414
  2.86206897  3.17241379  3.48275862  3.79310345  4.10344828  4.4137931
  4.72413793  5.03448276  5.34482759  5.65517241  5.96551724  6.27586207
  6.5862069   6.89655172  7.20689655  7.51724138  7.82758621  8.13793103
  8.44827586  8.75862069  9.06896552  9.37931034  9.68965517 10.        ]


## 3.Numpy.3




In [13]:
# print random values by different "functions"
# np.random.function(V1, V2, V3,......, Vn)

temp1 = np.random.rand(4) # sets 4 random values between 0 and 1
print(temp1)


[0.35740109 0.49920892 0.78502886 0.00872026]


In [14]:
temp2 = np.random.randint(10, 100, size=12) # sets 12 random values between 10 and 100
print(temp2) 

[18 93 48 57 56 52 28 47 88 79 44 38]


In [15]:
arr1 = np.array([[1, 4, 8], [2, 3, 4], [8, 3, 8], [1, 3, 87]])
print(arr1)

[[ 1  4  8]
 [ 2  3  4]
 [ 8  3  8]
 [ 1  3 87]]


In [17]:
print(arr1.reshape(2, 6)) # changes the shape of array from 4*3 to 2*6

[[ 1  4  8  2  3  4]
 [ 8  3  8  1  3 87]]


In [18]:
print(arr1.reshape(3, 4))  # changes the shape of array from 4*3 to 3*4

[[ 1  4  8  2]
 [ 3  4  8  3]
 [ 8  1  3 87]]


In [19]:
print(arr1.max()) # maximum value in the array 'arr1'
print(arr1.min()) # minimum value in the array 'arr1'

87
1


## 04. Numpy

In [20]:
# Indexing and Slicing
arr1 = np.arange(10, 30, 2)
print(arr1)
print(arr1[5]) # 6th element of the array

[10 12 14 16 18 20 22 24 26 28]
20


In [21]:
print(arr1[4:8]) # prints elements from 4 to 7th index

[18 20 22 24]


## 05.Numpy 

In [23]:
arr2 = np.arange(1, 21).reshape(4,5) # creating an array having values from 1 to 20 then coverting it into a 4*5 2-D array
print(arr2, '\n')

print(arr2[1][2])  # element at 2nd row and 3rd column

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]] 

8


In [24]:
arr2[0][0]=111 # sets the [0][0] element to 111
print(arr2) 

[[111   2   3   4   5]
 [  6   7   8   9  10]
 [ 11  12  13  14  15]
 [ 16  17  18  19  20]]


## 06.Numpy

In [25]:
# Slicing in 2-D arrays
arr = np.arange(1, 21).reshape(4, 5) # creating an array having values from 1 to 20 then coverting it into a 4*5 2-D array
print(arr)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]


In [27]:
print(arr[2:4, :3]) # slices the array 3rd and 4th rows and first three columns

[[11 12 13]
 [16 17 18]]


In [28]:
print(arr[:1]) # slices the first row

[[1 2 3 4 5]]


In [29]:
print(arr[:, 0:1])  # slices the first column

[[ 1]
 [ 6]
 [11]
 [16]]


## 07.Numpy

In [30]:
arr=np.arange(1, 20, 3)
print(arr)
print(arr+5)  # increments each element of arr by 5

[ 1  4  7 10 13 16 19]
[ 6  9 12 15 18 21 24]


In [31]:
arr1 = np.arange(1, 20, 3)
arr2 = np.arange(20, 40, 3)

print(arr1, '\n')
print(arr2, '\n')
print(arr1+arr2, '\n') # adds corresponding elements of arr1 and arr2  ( both arrays should have same number of elements !!! )
print(arr1-arr2, '\n') # subtracts corresponding elements of arr1 and arr2  ( both arrays should have same number of elements !!! )
print(arr1*arr2, '\n') # multiplies corresponding elements of arr1 and arr2  ( both arrays should have same number of elements !!! )

[ 1  4  7 10 13 16 19] 

[20 23 26 29 32 35 38] 

[21 27 33 39 45 51 57] 

[-19 -19 -19 -19 -19 -19 -19] 

[ 20  92 182 290 416 560 722] 



In [32]:
print(arr1**4) # exponentiate elements arr2 by 4

[     1    256   2401  10000  28561  65536 130321]


In [34]:
# Using Conditionls
print(arr2[arr2>5], '\n') # prints all the elements in the array 'arr2' which are greater than 5
print(arr2[arr2%2==0]) # prints all the even elements in the array 'arr2'

[20 23 26 29 32 35 38] 

[20 26 32 38]


In [36]:
print(arr2, '\n')
print(np.power(arr2, 4)) # each element of arr2 raised to power 4

SyntaxError: invalid syntax (Temp/ipykernel_4336/3601937021.py, line 1)