# **WEEK 1, 2, 3, 4**

In [1]:
import torch
print("Using torch", torch.__version__)

Using torch 1.13.1+cu117


In [2]:
a= torch.tensor([1, 2, 4, 5, 7, 8])
print(a.dtype)
print(a.type())

torch.int64
torch.LongTensor


In [3]:
a= torch.tensor([1.0, 2.0, 4.0, 5.0, 7.0, 8.0])
print(a.dtype)
print(a.type())

torch.float32
torch.FloatTensor


In [4]:
a= torch.tensor([1.0, 2.0, 4.0, 5.0, 7.0, 8.0], dtype= torch.int32)
print(a.dtype)
print(a.type())
print(a)

torch.int32
torch.IntTensor
tensor([1, 2, 4, 5, 7, 8], dtype=torch.int32)


C:\Users\deepa\AppData\Local\Temp\ipykernel_22164\1309466264.py:1: DeprecationWarning: an integer is required (got type float).  Implicit conversion to integers using __int__ is deprecated, and may be removed in a future version of Python.
  a= torch.tensor([1.0, 2.0, 4.0, 5.0, 7.0, 8.0], dtype= torch.int32)


In [5]:
a= torch.FloatTensor([1, 2, 4, 5, 7, 8])
print(a.dtype)
print(a.type())

torch.float32
torch.FloatTensor


In [6]:
import numpy as np
import torch

np_arr = np.array([[1, 2], [3, 4]])
tensor = torch.from_numpy(np_arr)

print("Numpy array:", np_arr)
print("PyTorch tensor:", tensor)

Numpy array: [[1 2]
 [3 4]]
PyTorch tensor: tensor([[1, 2],
        [3, 4]], dtype=torch.int32)


In [7]:
class LinearRegressionModel(torch.nn.Module):

	def __init__(self):
		super(LinearRegressionModel, self).__init__()
		self.linear = torch.nn.Linear(1, 1) # One in and one out

	def forward(self, x):
		y_pred = self.linear(x)
		return y_pred


In [8]:
import torch
from torch.autograd import Variable
x_data = Variable(torch.Tensor([[1.0], [2.0], [3.0]]))
y_data = Variable(torch.Tensor([[2.0], [4.0], [6.0]]))

In [9]:
class LinearRegressionModel(torch.nn.Module):

	def __init__(self):
		super(LinearRegressionModel, self).__init__()
		self.linear = torch.nn.Linear(1, 1) # One in and one out

	def forward(self, x):
		y_pred = self.linear(x)
		return y_pred

In [10]:
model= LinearRegressionModel()
criterion = torch.nn.MSELoss(size_average = False)
optimizer = torch.optim.SGD(model.parameters(), lr = 0.01)


c:\Users\deepa\AppData\Local\Programs\Python\Python39\lib\site-packages\torch\nn\_reduction.py:42: UserWarning: size_average and reduce args will be deprecated, please use reduction='sum' instead.
  warnings.warn(warning.format(ret))


In [11]:

for epoch in range(500):
 
    # Forward pass: Compute predicted y by passing
    # x to the model
    pred_y = model(x_data)
 
    # Compute and print loss
    loss = criterion(pred_y, y_data)
 
    # Zero gradients, perform a backward pass,
    # and update the weights.
    optimizer.zero_grad()
    loss.backward()
    optimizer.step()
    print('epoch {}, loss {}'.format(epoch, loss.item()))
 
new_var = Variable(torch.Tensor([[4.0]]))
pred_y = model(new_var)
print("predict (after training)", 4, model(new_var).item())

epoch 0, loss 36.46397018432617
epoch 1, loss 16.270137786865234
epoch 2, loss 7.279878616333008
epoch 3, loss 3.2771430015563965
epoch 4, loss 1.4947155714035034
epoch 5, loss 0.7007136344909668
epoch 6, loss 0.3467392921447754
epoch 7, loss 0.18866035342216492
epoch 8, loss 0.11779484897851944
epoch 9, loss 0.08576150238513947
epoch 10, loss 0.0710224136710167
epoch 11, loss 0.06398893147706985
epoch 12, loss 0.060392674058675766
epoch 13, loss 0.05833315849304199
epoch 14, loss 0.056964270770549774
epoch 15, loss 0.05590951815247536
epoch 16, loss 0.055000875145196915
epoch 17, loss 0.05416354537010193
epoch 18, loss 0.05336438864469528
epoch 19, loss 0.05258810520172119
epoch 20, loss 0.05182824283838272
epoch 21, loss 0.05108163133263588
epoch 22, loss 0.05034665763378143
epoch 23, loss 0.04962257295846939
epoch 24, loss 0.048909373581409454
epoch 25, loss 0.04820649325847626
epoch 26, loss 0.04751357063651085
epoch 27, loss 0.04683076590299606
epoch 28, loss 0.04615764319896698
e

In [19]:
# logistic regression class
import torch.nn as nn
class LogisticRegression(nn.Module):
    def __init__(self, n_input_features):
        super(LogisticRegression, self).__init__()
        self.linear = nn.Linear(n_input_features, 1)
    
    #sigmoid transformation of the input 
    def forward(self, x):
        y_pred = torch.sigmoid(self.linear(x))
        return y_pred

model= LinearRegressionModel()
list(model.parameters())

[Parameter containing:
 tensor([[-0.2907]], requires_grad=True),
 Parameter containing:
 tensor([0.0678], requires_grad=True)]

In [17]:
num_epochs = 500                                        
learning_rate = 0.0001                               
criterion = nn.BCELoss() # Binary Cross entropy loss                         
optimizer = torch.optim.SGD(model.parameters(), lr=learning_rate)      